modLoader="javafml"
loaderVersion="[33,)"
license="MIT"

[[mods]]
modId="minecraft_test"
version="${version}"
displayName="${name}"
authors="xtrm"
description='''
gayming!
'''

[[dependencies.minecraft_test]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="BOTH"

[[dependencies.minecraft_test]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"